export const TEST = 'TEST';
export const RESET = 'RESET';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const TOGGLE_FEEDBACK_MODAL = 'TOGGLE_FEEDBACK_MODAL';
export const CHANGE_MODAL_DETAILS = 'CHANGE_MODAL_DETAILS'
